// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZ_-WzQNVGzFHuGGLt2AGp2OVQnPV5rg',
    appId: '1:908002770933:web:e59a5dfaf594a931d66abc',
    messagingSenderId: '908002770933',
    projectId: 'food-app-131b5',
    authDomain: 'food-app-131b5.firebaseapp.com',
    storageBucket: 'food-app-131b5.appspot.com',
    measurementId: 'G-LGH1VF9JCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7CYg-hJmMmWjGrLxC_syW0MKFA0nY_ZM',
    appId: '1:908002770933:android:49a6ffd0da63364dd66abc',
    messagingSenderId: '908002770933',
    projectId: 'food-app-131b5',
    storageBucket: 'food-app-131b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDth6AsQKLo9CD0GyXK8D6rrxYHasvYaYg',
    appId: '1:908002770933:ios:4ae0a94dbe1f3412d66abc',
    messagingSenderId: '908002770933',
    projectId: 'food-app-131b5',
    storageBucket: 'food-app-131b5.appspot.com',
    iosClientId: '908002770933-o6ejah5fp4a15pc96jv5dutmc4acbgtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodAppApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDth6AsQKLo9CD0GyXK8D6rrxYHasvYaYg',
    appId: '1:908002770933:ios:4ae0a94dbe1f3412d66abc',
    messagingSenderId: '908002770933',
    projectId: 'food-app-131b5',
    storageBucket: 'food-app-131b5.appspot.com',
    iosClientId: '908002770933-o6ejah5fp4a15pc96jv5dutmc4acbgtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodAppApi',
  );
}
